language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev" 
  - "2.6"
  - "3.2"
  - "3.5"
  - "nightly"
install:
  - pip install .
script:
  - python -W default::Warning -m coverage run --branch -m pytest --tb short
  - python -m coverage report --include 'chatexchange6/*'
branches:
  only:
    - master
env:
  global:
    - secure: "l3wVjDs94gpM1p+lmjBHPDJm65qMb4hCc9c6IA+0IAKCnLX0CNqzn5H4R3JIswOb9d8nMyF1iU/wwv7KBoZTnm8dSqoiv+puD82xc+auR3fF/pcxK2jZq6qgXTRlfgAst80qJbH2g5mNLLI30/mSHoHI/5FWLmjaoeifA4O1rkE="
    - secure: "av9hxTZp/Dhe9xAOq6WlhTNDoWjjczN3lFanG6h/3h4kW7DsxhfXMRA96z6MambbC6c9ARFiwsQ24NeCAfPQ1m6r9uZwNkusqnRDOwZQeVQcmopnoNNG4Kd/9oclIVgsAlSG6WfhkyQPUG2p7PkOvxFV4/YjDSViYDR3eoih3JA="
notifications:
  email: false
