language: python
python:
  - '2.7'
install:
  - 'pip install .'
script:
  - 'py.test --tb short'
branches:
  only:
    - master
    - test
env:
  secure: "GOLhyebFPgHT8AZp6Kq9O9C0T6h7/fzh84L4cR4/QrmHFQKvxOy42T5Uh/oB5w/xoQ94G3e0w3eAJQnu9LF+pCGHwGMXoDSI9o3k6XNmgz1FHqI62bBIID/kpuQ6+t/dv2/fdqGA7mIujTFqbMUMNJaALJ5NEIqi6I921Rcs/s0="
